
# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import argparse
import os
import sys
import sphinx_rtd_theme
sys.path.insert(0, os.path.abspath('.'))
#sys.path.insert(0, os.path.abspath('../_static'))
#sys.path.insert(0, os.path.abspath('../fonts'))
#sys.path.insert(0, os.path.abspath('../images'))

#on_rtd = os.environ.get('READTHEDOCS') == 'True'
#if on_rtd:
#    print('acd CONF ======================================')
#    # we are in 'en' currently)
#    print('acd CONF {}'.format(os.path.abspath('.')))
#    os.system('ls -la *')
#    print('acd CONF ======================================')
#else:
#    html_theme = 'default'

#if "install" in sys.argv:
if 'READTHEDOCS' in os.environ:
    print('acd SETUP ======================================')
    os.system('cp -a ../_static ../fonts ../images .')
    #os.system('rm -rf ../ru')
    os.system('bash ./pre.sh html .')
    #os.system('bash ./pre.sh epub en')
    print('acd SETUP {}'.format(os.path.abspath('.')))
    os.system('ls -la .')
    print('/acd SETUP ======================================')

# -- Project information -----------------------------------------------------

project = 'Bona Fide Guru'
copyright = '2022, Abhay Charan das'
author = 'Yagyasena -- Prabhupāda das'

# The full version, including alpha/beta/rc tags
release = '2022.02.19'

show_authors = False
smartquotes = True

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx_rtd_theme'] #, 'sphinxcontrib.programoutput']
# Now you’ve two new directives:
#  .. program-output:: python -V
#  .. command-output:: python -V
#to insert the output of programs.


# Add any paths that contain templates here, relative to this directory.
#templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'ru', 'en', '_templates', 'site', 'fonts', 'README.rst']

# Enable figures numbering
numfig = True

# Date format if `today` not set
today_fmt = "%Y-%m-%d"

# PDF build from the LaTeX files created by Sphinx will use xindy (doc) rather than makeindex for preparing the index of general terms (from index usage). 
latex_use_xindy = True

text_add_secnumbers = False

latex_engine = 'xelatex'

# Grouping the document tree into LaTeX files. List of tuples# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
 ('index', 'bonafide.guru.tex', u'Bona Fide Guru', u'Yagyasena -- Prabhupāda das', 'manual', False),
]

latex_additional_files = [
    "images/logo.png",
    "images/_july9th.jpg",
    "images/_will1.jpg",
    "images/_will2.jpg",
    "style.tex.txt",
]

latex_elements = {
    'passoptionstopackages': r'\usepackage[pdfa=true,dvipdfmx-outline-open,bookmarks=true,bookmarksopen=true,bookmarksopenlevel=2,unicode=true,pdfusetitle=true,hidelinks=true,pdfkeywords={Гаўдӣйа-Ваишн̣авизм, ISKCON,Международное Общество для Осознания Кришны, Его Божественная Милость Ш́рӣ Ш́рӣмад А.Ч. Бхактиведанта Свами Прабхупа̄да, Дӣкша̄-гуру, Bona fide Guru},pdfsubject={подношение лотосным стопам Основателя-А̄ча̄рйи ISKCON Его Божественной Милости Ш́рӣ Ш́рӣмад А.Ч. Бхактиведанта Свами Ш́рӣлы Прабхупа̄ды},]{hyperref}',

    # A5 paper size
    "papersize": "a5paper",
    # Oneside pages
    #"classoptions": ",twoside",
    # Custom preamble to tune title page
#    "preamble": preamble,
    # The font size ('10pt', '11pt' or '12pt').
    "pointsize": "10pt",

    # https://www.sphinx-doc.org/en/master/latex.html
    'makeindex': '\\usepackage[columns=1]{idxlayout}\\makeindex',
    'printindex': '\\renewcommand{\\indexname}{Указатель цитируемых санскритских стихов}\\small\\raggedright\\printindex',
    # Disable Index page
    #"printindex": "",

    # https://www.sphinx-doc.org/en/master/latex.html
    # The dimensions of the horizontal and vertical margins passed to the geometry package:
    # Default: 1in,1in,0.5in
    'sphinxsetup': 'hmargin={0.5in,0.5in}, vmargin={0.5in,0.5in}',

    'preamble': r'''
        \setlength{\headsep}{15pt} % 25
        \setlength{\footskip}{20pt} % 30
        \addtolength{\topmargin}{18pt} % 16+18

        \usepackage{xltxtra}
        \usepackage{xunicode}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \usepackage{polyglossia}
  \setdefaultlanguage{russian}
  \setotherlanguages{english}
  %\setotherlanguages{english,hindi,sanskrit}
  %\newfontfamily\devanagarifont[Script=Devanagari]{Lohit Devanagari}

  \usepackage{fontspec}

 \setmainfont{FreeMono}[
   Path = /usr/share/fonts/truetype/freefont/,
   Extension = .ttf,
   UprightFont = *,
   %-- Upright --%
   FontFace={m}{n}{Font=*},
   FontFace={b}{n}{Font=*Bold},
   % %-- Italic --%
   FontFace={m}{it}{Font=*Oblique},
   FontFace={b}{it}{Font=*BoldOblique},
  ]

 \setmainfont{Andika}[
   Path = ./fonts/Andika-6.001/,
   Extension = .ttf,
   UprightFont = *-Regular,
   %-- Upright --%
   FontFace={m}{n}{Font=*-Regular},
   FontFace={b}{n}{Font=*-Bold},
   % %-- Italic --%
   FontFace={m}{it}{Font=*-Italic},
   FontFace={b}{it}{Font=*-BoldItalic},
  ]

  \setmainfont{CharisSIL}[
   Path = ./fonts/CharisSIL-6.101/,
   Extension = .ttf,
   UprightFont = *-Regular,
   %-- Upright --%
   FontFace={m}{n}{Font=*-Regular},
   FontFace={b}{n}{Font=*-Bold},
   % %-- Italic --%
   FontFace={m}{it}{Font=*-Italic},
   FontFace={b}{it}{Font=*-BoldItalic},
  ]

  \setromanfont{CharisSIL}
  \setsansfont{Andika}
  \setmonofont{FreeMono}

  \newfontfamily{\cyrillicfont}{CharisSIL}
  \newfontfamily{\cyrillicfontrm}{CharisSIL}
  \newfontfamily{\cyrillicfontsf}{Andika}
  \newfontfamily{\cyrillicfonttt}{FreeMono}

  \newfontface\tnrfam{Times New Roman}
  \newfontface\tnrItalicfam{Times New Roman Italic}
  \newfontface\tnrBoldfam{Times New Roman Bold}
  \newfontface\tnrBIfam{Times New Roman Bold Italic}
  \newcommand*\BonafideGuru{%
    {\tnrBoldfam Bona Fide Guru}%
  }%
  \newcommand*\BonafideGuruN{%
    {\tnrfam Bona Fide Guru}%
  }%
  \newcommand*\Yagyasena{%
    {Yagyasena \textendash~Prabhupāda das}%
  }%

  \newcommand\decorCenterRuler{%
        \hrulefill
        \raisebox{-2.1pt}
        {\quad\decofourleft\decotwo\decofourright\quad}%
        \hrulefill}
  \newcommand\decorCenter{%
        \strut\hfill
        \raisebox{-2.1pt}
        {\quad\decofourleft\decotwo\decofourright\quad}%
        \hfill\strut}
  \newcommand\myoldpilcrowfour{%
           \noindent {\oldpilcrowfour}\,}
  \newcommand\myoldpilcrowfive{%
           \noindent {\oldpilcrowfive}\,}
  \newcommand\myoldpilcrowsix{%
           \noindent {\oldpilcrowsix}\,}

  \usepackage{fourier-orns}
  \usepackage{pgfornament}
  \usepackage{eso-pic}
  \newcommand\AtPageUpperRight[1]{\AtPageUpperLeft{%
   \put(\LenToUnit{\paperwidth},\LenToUnit{0\paperheight}){#1}%
   }}%
  \newcommand\AtPageLowerRight[1]{\AtPageLowerLeft{%
   \put(\LenToUnit{\paperwidth},\LenToUnit{0\paperheight}){#1}%
   }}%
  \newcommand{\beautify}{%
   \AddToShipoutPictureBG{%
     \AtPageUpperLeft{\put(0,-25){\pgfornament[width=1.75cm]{61}}}
     \AtPageUpperRight{\put(-50,-25){\pgfornament[width=1.75cm,symmetry=v]{61}}}
     \AtPageLowerLeft{\put(0,25){\pgfornament[width=1.75cm,symmetry=h]{61}}}
     \AtPageLowerRight{\put(-50,25){\pgfornament[width=1.75cm,symmetry=c]{61}}}
   }
  }

  \newcommand{\simplify}{%
     \cleardoublepage\ClearShipoutPictureBG
  }

  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhf{}
  \makeatletter
   \fancypagestyle{normal}{
    \fancyhf{}% clear all header and footer fields
    \renewcommand{\headrulewidth}{0pt}
    \renewcommand{\footrulewidth}{0pt}
    \renewcommand{\headrule}{} % disappear
    \renewcommand{\footrule}{} % disappear
    \fancyhead[LE,RO]{\thepage}
%    \renewcommand\footrule{%
%        \hrulefill
%        \raisebox{-2.1pt}
%        {\quad\decofourleft\decotwo\decofourright\quad}%
%        \hrulefill}
   }
   \fancypagestyle{plain}{%
    \fancyhf{}% clear all header and footer fields
%    \fancyfoot[C]{\textbf{--~\thepage~--}} % except the center
    \renewcommand{\headrulewidth}{0pt}%
    \renewcommand{\footrulewidth}{0pt}%
   }
  \makeatother

  \defaultfontfeatures{Scale=MatchLowercase, Mapping=tex-text}

  \input{style.tex.txt}

  \usepackage{titlesec, blindtext, color}

  \titleformat{\chapter}[frame]
    {\normalfont\bfseries}
    {}
    {8pt}
    {\Huge\bfseries\filcenter}

  \titleformat{\section}
  {\normalfont\Large\bfseries}{\thesection}{1em}{}
  \titleformat{\subsection}
  {\normalfont\large\bfseries}{\thesubsection}{1em}{}
  \titleformat{\subsubsection}
  {\normalfont\normalsize\bfseries}{\thesubsubsection}{1em}{}
  \titleformat{\paragraph}[runin]
  {\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
  \titleformat{\subparagraph}[runin]
  {\normalfont\normalsize\bfseries}{\thesubparagraph}{1em}{}

  %\titlespacing*{\chapter} {0pt}{50pt}{40pt}
  \titlespacing*{\section} {0pt}{3.5ex plus 1ex minus .2ex}{2.3ex plus .2ex}
  \titlespacing*{\subsection} {0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
  \titlespacing*{\subsubsection}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
  \titlespacing*{\paragraph} {0pt}{3.25ex plus 1ex minus .2ex}{1em}
  \titlespacing*{\subparagraph} {\parindent}{3.25ex plus 1ex minus .2ex}{1em}

  \def\changemargin#1#2{\list{}{\rightmargin#2\leftmargin#1}\item[]}
  \let\endchangemargin=\endlist

  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
''',
}

latex_show_urls = 'footnote'

rst_epilog = r"""
.. |noFrameStart| raw:: latex

   \begingroup
   \setlength{\arrayrulewidth}{0pt}

.. |noFrameEnd| raw:: latex

   \endgroup
"""
rst_prolog = """
"""

version = '2-е издание'
# -- Options for HTML output -------------------------------------------------

#html_baseurl = '/html/'
html_title = 'Bona Fide Guru'

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    #'analytics_id': 'G-XXXXXXXXXX',  #  Provided by Google in your dashboard
    #'analytics_anonymize_ip': False,
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    #'style_nav_header_background': '#2980B9', # '#f2ccbb' '#fcfcfc' #55a5d9
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}
#html_logo = '_static/cover-390x285.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
html_extra_path = ['_extra']

#html_js_files = [ 'js/custom.js', ]
html_css_files = [ 'html.css', ]   # this one is additional CSS
#html_style = 'html.css'           # this one replaces theme CSS

html_favicon = '_static/favicon32.ico'

#html_additional_pages = {
#    'download': 'customdownload.html',
#}
html_copy_source = False
html_show_sourcelink = False
html_show_copyright = True
html_show_sphinx = True

# -- Options for ePub output -------------------------------------------------

epub_theme = 'epub'
epub_language = 'en'
epub_cover = ('_static/epub-cover-650x475.png', 'epub-cover.html')

#epub_pre_files = [
#]
#epub_post_files  = [
#]

epub_title = 'Bona Fide Guru'
epub_author = 'Yagyasena-Prabhupāda das'
epub_contributor  = 'Abhay Charan das'
epub3_contributor = 'Abhay Charan das'
epub_publisher = 'Abhay Charan das'
epub_copyright =  '2022, Abhay Charan das'
epub_identifier = 'www.bonafide.guru' # or ISBN
epub_scheme = 'URL' # scheme for the 'epub_identifier'
#epub_uid = 'His Divine Grace Śrī Śrīmad A.C. Bhaktivedanta Swami Prabhupāda, ISKCON, Founder-Ācārya of the International Society for Krishna Consciousness, Bona fide Guru, Diksha Guru, Gauḍīya Vaiṣṇavism'
epub_uid = epub_identifier
epub_description = 'offering to the lotus feet of the Founder-Ācārya ISKCON His Divine Grace Śrī Śrīmad A.C. Bhaktivedanta Swami Prabhupāda'
epub3_description = epub_description
#epub_show_urls
#Control whether to display URL addresses. This is very useful for readers that have no other means to display the linked URL. The settings can have the following values:
# - 'inline' – display URLs inline in parentheses (default)
# - 'footnote' – display URLs in footnotes
# - 'no' – do not display URLs

